export const BASE_URL = import.meta.env.VITE_BACKEND_URL || "http://localhost:8000";

export const API_PATHS = {
  AUTH: {
    LOGIN: "/api/v1/auth/login",
    LOGOUT: "/api/v1/auth/logout",
    CREATE_USER: "/api/v1/auth/signup",
    CREATE_SCHOOL: "/api/v1/auth/signup-school",
    GET_USER_INFO: "/api/v1/auth/getUserInfo",
  },
  GAMES: {
    GET_ALL_GAMES: "/api/v1/games",
    GET_ACTIVE_GAME: "/api/v1/games/active",
    ACTIVATE_GAME: (gameId) => `/api/v1/games/activate/${gameId}`,
    DEACTIVATE_GAME: (gameId) => `/api/v1/games/deactivate/${gameId}`,
    COMPLETE_GAME: (gameId) => `/api/v1/games/complete/${gameId}`,
  },
  ADMIN: {
    GET_ALL_USERS: "/api/v1/admin/users",
    GET_ALL_JUDGES: "/api/v1/admin/judges",
    GET_ALL_SCHOOLS: "/api/v1/admin/schools",
    EDIT_SCHOOL: (id) => `/api/v1/admin/schools/${id}`,
    EDIT_USER: (id) => `/api/v1/admin/users/${id}`,
    DELETE_USER: (id) => `/api/v1/admin/user/${id}`,
    DELETE_SCHOOL: (id) => `/api/v1/admin/school/${id}`,
    GET_SCHOOL_SCORES: "/api/v1/admin/dashboard",
    SHOW_WINNERS: "/api/v1/admin/winners",
  },
  CRITERIA: {
    GET_ALL: "/api/v1/criteria",
    CREATE: "/api/v1/criteria",
    UPDATE: (id) => `/api/v1/criteria/${id}`,
    DELETE: (id) => `/api/v1/criteria/${id}`,
  },
  BATTLE_BREAKERS: {
    GET_QUESTIONS: "/api/v1/battle-breakers",
    GET_ANSWERS: "/api/v1/battle-breakers/answers",
    ADD_QUESTION: "/api/v1/battle-breakers/addQuestion",
    UPLOAD_CSV: "/api/v1/battle-breakers/uploadCSV",
    EDIT_QUESTION: (questionId) => `/api/v1/battle-breakers/editQuestion/${questionId}`,
    DELETE_QUESTION: (questionId) => `/api/v1/battle-breakers/deleteQuestion/${questionId}`,
    DELETE_ALL_QUESTIONS: "/api/v1/battle-breakers/deleteAllQuestions",
    BUZZER_PRESS: "/api/v1/battle-breakers/press",
    GET_DASHBOARD: (questionId) => `/api/v1/battle-breakers/school/${questionId}`,
    SUBMIT_ANSWERS: "/api/v1/battle-breakers/submit",
    FINISH_GAME: "/api/v1/battle-breakers/finishGame",
    GET_ALLOCATED_TIME: "/api/v1/battle-breakers/allocatedTime",
  },
  QUIZ_HUNTERS: {
    GET_ALL_QUESTIONS: "/api/v1/quiz-hunters/",
    GET_Q_WITH_A: "/api/v1/quiz-hunters/QnA",
    ADD_QUESTION: "/api/v1/quiz-hunters/addQuestion",
    EDIT_QUESTION: (questionId) => `/api/v1/quiz-hunters/editQuestion/${questionId}`,
    DELETE_QUESTION: (questionId) => `/api/v1/quiz-hunters/deleteQuestion/${questionId}`,
    DELETE_ALL_QUESTIONS: "/api/v1/quiz-hunters/deleteAllQuestions",
    UPLOAD_CSV: "/api/v1/quiz-hunters/uploadCSV",
    SET_TIME: "/api/v1/quiz-hunters/setTime",
    GET_TIME: "/api/v1/quiz-hunters/time",
    SUBMIT: "/api/v1/quiz-hunters/submit",
    FINISH: "/api/v1/quiz-hunters/finish",
    CURRENT_QUESTION: "/api/v1/quiz-hunters/currentQuestion",
  },
  CODE_CRUSHERS: {
    GET_CRITERIA: "/api/v1/code-crushers/criteria",
    GET_SLIDES: "/api/v1/code-crushers/",
    UPLOAD_SLIDES: "/api/v1/code-crushers/slides",
    DELETE_ALL_SLIDES: "/api/v1/code-crushers/slides/delete",
    UPLOAD_RESOURCE: "/api/v1/code-crushers/upload",
    GET_ALL_RESOURCES: "/api/v1/code-crushers/resources",
    GET_RESOURCE_COUNT: "/api/v1/code-crushers/resources/count",
    GET_RESOURCE: (id) => `/api/v1/code-crushers/resources/${id}`,
    GET_MARKINGS: "/api/v1/code-crushers/markings",
    SET_TIME: "/api/v1/code-crushers/time",
    GET_TIME: "/api/v1/code-crushers/time",
  },
  CIRCUIT_SMASHERS: {
    GET_CRITERIA: "/api/v1/circuit-smashers/criteria",
    GET_SLIDES: "/api/v1/circuit-smashers/",
    UPLOAD_SLIDES: "/api/v1/circuit-smashers/slides",
    DELETE_ALL_SLIDES: "/api/v1/circuit-smashers/slides/delete",
    UPLOAD_RESOURCE: "/api/v1/circuit-smashers/upload",
    GET_ALL_RESOURCES: "/api/v1/circuit-smashers/resources",
    GET_RESOURCE_COUNT: "/api/v1/circuit-smashers/resources/count",
    GET_RESOURCE: (id) => `/api/v1/circuit-smashers/resources/${id}`,
    GET_MARKINGS: "/api/v1/circuit-smashers/markings",
    SET_TIME: "/api/v1/circuit-smashers/time",
    GET_TIME: "/api/v1/circuit-smashers/time",
  },
  ROUTE_SEEKERS: {
    SET_TIME: "/api/v1/route-seekers/time",
    GET_TIME: "/api/v1/route-seekers/time",
  },
  JUDGE: {
    SUBMIT_CODE_CRUSHERS_MARKS: "/api/v1/judge/code-crushers/",
    GET_CODE_CRUSHERS_MARKINGS: "/api/v1/judge/code-crushers/",
    SUBMIT_CIRCUIT_SMASHERS_MARKS_BULK: "/api/v1/judge/circuit-smashers/bulk",
    GET_CIRCUIT_SMASHERS_MARKINGS: "/api/v1/judge/circuit-smashers/",
  SUBMIT_ROUTE_SEEKERS_MARKS: "/api/v1/judge/route-seekers/", // (legacy quiz part?)
  GET_ROUTE_SEEKERS_MARKINGS: "/api/v1/judge/route-seekers/", // (legacy quiz part?)
  SUBMIT_ROUTE_SEEKERS_NETWORK_DESIGN_MARKS: "/api/v1/judge/route-seekers-network-design/",
  GET_ROUTE_SEEKERS_NETWORK_DESIGN_MARKINGS: "/api/v1/judge/route-seekers-network-design/",
    GET_QUIZ_HUNTERS_MARKINGS: "/api/v1/judge/quiz-hunters/",
  }
};